export interface CompanyMetadata {
    name: string;
    domain: string; // The primary domain to fetch logos from (e.g. apple.com)
    patterns: string[]; // URL substrings for matching
}

export const COMPANY_REGISTRY: CompanyMetadata[] = [
    { name: 'Amazon', domain: 'amazon.com', patterns: ['amazon.jobs'] },
    { name: 'Google', domain: 'google.com', patterns: ['careers.google.com', 'google.com/careers'] },
    { name: 'Microsoft', domain: 'microsoft.com', patterns: ['careers.microsoft.com'] },
    { name: 'Apple', domain: 'apple.com', patterns: ['jobs.apple.com', 'apple.com/careers'] },
    { name: 'Meta', domain: 'meta.com', patterns: ['metacareers.com', 'facebook.com/careers'] },
    { name: 'Netflix', domain: 'netflix.com', patterns: ['jobs.netflix.com'] },
    { name: 'LinkedIn', domain: 'linkedin.com', patterns: ['careers.linkedin.com'] },
    { name: 'Adobe', domain: 'adobe.com', patterns: ['careers.adobe.com'] },
    { name: 'Salesforce', domain: 'salesforce.com', patterns: ['careers.salesforce.com'] },
    { name: 'Oracle', domain: 'oracle.com', patterns: ['oracle.com/corporate/careers'] },
    { name: 'IBM', domain: 'ibm.com', patterns: ['ibm.com/careers'] },
    { name: 'Intel', domain: 'intel.com', patterns: ['jobs.intel.com'] },
    { name: 'Nvidia', domain: 'nvidia.com', patterns: ['nvidia.com/en-us/about-nvidia/careers'] },
    { name: 'AMD', domain: 'amd.com', patterns: ['careers.amd.com'] },
    { name: 'Qualcomm', domain: 'qualcomm.com', patterns: ['qualcomm.com/company/careers'] },
    { name: 'Samsung', domain: 'samsung.com', patterns: ['samsungcareers.com'] },
    { name: 'HP', domain: 'hp.com', patterns: ['jobs.hp.com'] },
    { name: 'Dell', domain: 'dell.com', patterns: ['jobs.dell.com'] },
    { name: 'TikTok', domain: 'tiktok.com', patterns: ['careers.tiktok.com'] },
    { name: 'Snap', domain: 'snap.com', patterns: ['careers.snap.com'] },
    { name: 'Spotify', domain: 'spotify.com', patterns: ['lifeatspotify.com'] },
    { name: 'Airbnb', domain: 'airbnb.com', patterns: ['careers.airbnb.com'] },
    { name: 'Uber', domain: 'uber.com', patterns: ['uber.com/us/en/careers'] },
    { name: 'Lyft', domain: 'lyft.com', patterns: ['lyft.com/careers'] },
    { name: 'Pinterest', domain: 'pinterest.com', patterns: ['careers.pinterest.com'] },
    { name: 'Dropbox', domain: 'dropbox.com', patterns: ['jobs.dropbox.com'] },
    { name: 'Automattic', domain: 'automattic.com', patterns: ['automattic.com/work-with-us'] },
    { name: 'Stripe', domain: 'stripe.com', patterns: ['stripe.com/jobs'] },
    { name: 'Block', domain: 'block.xyz', patterns: ['careers.block.xyz'] },
    { name: 'Atlassian', domain: 'atlassian.com', patterns: ['atlassian.com/company/careers'] },
    { name: 'Cloudflare', domain: 'cloudflare.com', patterns: ['cloudflare.com/careers'] },
    { name: 'Twilio', domain: 'twilio.com', patterns: ['twilio.com/company/jobs'] },
    { name: 'Zoom', domain: 'zoom.us', patterns: ['careers.zoom.us'] },
    { name: 'Workday', domain: 'workday.com', patterns: ['workday.com/en-us/company/careers'] },
    { name: 'Snowflake', domain: 'snowflake.com', patterns: ['careers.snowflake.com'] },
    { name: 'HubSpot', domain: 'hubspot.com', patterns: ['hubspot.com/careers'] },
    { name: 'Shopify', domain: 'shopify.com', patterns: ['shopify.com/careers'] },
    { name: 'ServiceNow', domain: 'servicenow.com', patterns: ['servicenow.com/careers'] },
    { name: 'SAP', domain: 'sap.com', patterns: ['jobs.sap.com'] },
    { name: 'Goldman Sachs', domain: 'goldmansachs.com', patterns: ['goldmansachs.com/careers'] },
    { name: 'JPMorgan Chase', domain: 'jpmorgan.com', patterns: ['careers.jpmorgan.com'] },
    { name: 'Morgan Stanley', domain: 'morganstanley.com', patterns: ['morganstanley.com/people-opportunities'] },
    { name: 'Citi', domain: 'citi.com', patterns: ['jobs.citi.com'] },
    { name: 'Bank of America', domain: 'bankofamerica.com', patterns: ['careers.bankofamerica.com'] },
    { name: 'Wells Fargo', domain: 'wellsfargo.com', patterns: ['wellsfargo.com/about/careers'] },
    { name: 'Capital One', domain: 'capitalone.com', patterns: ['capitalonecareers.com'] },
    { name: 'American Express', domain: 'americanexpress.com', patterns: ['americanexpress.com/en-us/careers'] },
    { name: 'Visa', domain: 'visa.com', patterns: ['visa.com/careers'] },
    { name: 'Mastercard', domain: 'mastercard.com', patterns: ['careers.mastercard.com'] },
    { name: 'PayPal', domain: 'paypal.com', patterns: ['paypal.com/us/webapps/mpp/jobs'] },
    { name: 'Fidelity', domain: 'fidelity.com', patterns: ['jobs.fidelity.com'] },
    { name: 'BlackRock', domain: 'blackrock.com', patterns: ['blackrock.com/corporate/careers'] },
    { name: 'Accenture', domain: 'accenture.com', patterns: ['accenture.com/us-en/careers'] },
    { name: 'McKinsey', domain: 'mckinsey.com', patterns: ['mckinsey.com/careers'] },
    { name: 'BCG', domain: 'bcg.com', patterns: ['bcg.com/careers'] },
    { name: 'Bain', domain: 'bain.com', patterns: ['bain.com/careers'] },
    { name: 'Deloitte', domain: 'deloitte.com', patterns: ['deloitte.com/us/en/careers'] },
    { name: 'PwC', domain: 'pwc.com', patterns: ['pwc.com/us/en/careers'] },
    { name: 'EY', domain: 'ey.com', patterns: ['ey.com/en_us/careers'] },
    { name: 'KPMG', domain: 'kpmg.com', patterns: ['kpmgcareers.com'] },
    { name: 'Cognizant', domain: 'cognizant.com', patterns: ['careers.cognizant.com'] },
    { name: 'Walmart', domain: 'walmart.com', patterns: ['careers.walmart.com'] },
    { name: 'Target', domain: 'target.com', patterns: ['jobs.target.com'] },
    { name: 'Home Depot', domain: 'homedepot.com', patterns: ['careers.homedepot.com'] },
    { name: 'Lowe\'s', domain: 'lowes.com', patterns: ['talent.lowes.com'] },
    { name: 'Starbucks', domain: 'starbucks.com', patterns: ['starbucks.com/careers'] },
    { name: 'Costco', domain: 'costco.com', patterns: ['costco.com/jobs'] },
    { name: 'Kroger', domain: 'kroger.com', patterns: ['jobs.kroger.com'] },
    { name: 'Disney', domain: 'disney.com', patterns: ['jobs.disneycareers.com'] },
    { name: 'Nike', domain: 'nike.com', patterns: ['jobs.nike.com'] },
    { name: 'CVS Health', domain: 'cvshealth.com', patterns: ['jobs.cvshealth.com'] },
    { name: 'UnitedHealth Group', domain: 'unitedhealthgroup.com', patterns: ['careers.unitedhealthgroup.com'] },
    { name: 'Johnson & Johnson', domain: 'jnj.com', patterns: ['jobs.jnj.com'] },
    { name: 'Pfizer', domain: 'pfizer.com', patterns: ['pfizer.com/careers'] },
    { name: 'Novartis', domain: 'novartis.com', patterns: ['novartis.com/careers'] },
    { name: 'Roche', domain: 'roche.com', patterns: ['roche.com/careers'] },
    { name: 'Merck', domain: 'merck.com', patterns: ['merck.com/careers'] },
    { name: 'AbbVie', domain: 'abbvie.com', patterns: ['abbvie.com/careers'] },
    { name: 'GSK', domain: 'gsk.com', patterns: ['jobs.gsk.com'] },
    { name: 'AstraZeneca', domain: 'astrazeneca.com', patterns: ['careers.astrazeneca.com'] },
    { name: 'Boeing', domain: 'boeing.com', patterns: ['jobs.boeing.com'] },
    { name: 'Lockheed Martin', domain: 'lockheedmartin.com', patterns: ['lockheedmartinjobs.com'] },
    { name: 'Northrop Grumman', domain: 'northropgrumman.com', patterns: ['northropgrumman.com/careers'] },
    { name: 'RTX', domain: 'rtx.com', patterns: ['careers.rtx.com'] },
    { name: 'SpaceX', domain: 'spacex.com', patterns: ['spacex.com/careers'] },
    { name: 'Tesla', domain: 'tesla.com', patterns: ['tesla.com/careers'] },
    { name: 'Ford', domain: 'ford.com', patterns: ['corporate.ford.com/careers'] },
    { name: 'GM', domain: 'gm.com', patterns: ['search-careers.gm.com'] },
    { name: 'Toyota', domain: 'toyota.com', patterns: ['toyota.com/careers'] },
    { name: 'Honda', domain: 'honda.com', patterns: ['honda.com/careers'] },
    { name: 'USAJOBS', domain: 'usajobs.gov', patterns: ['usajobs.gov'] },
    { name: 'PepsiCo', domain: 'pepsico.com', patterns: ['pepsicojobs.com'] },
    { name: 'Coca-Cola', domain: 'coca-cola.com', patterns: ['careers.coca-colacompany.com'] },
    { name: 'Unilever', domain: 'unilever.com', patterns: ['jobs.unilever.com'] },
    { name: 'P&G', domain: 'pg.com', patterns: ['pgcareers.com'] },
    { name: 'Nestlé', domain: 'nestle.com', patterns: ['nestle.com/jobs'] },
    { name: 'Shell', domain: 'shell.com', patterns: ['jobs.shell.com'] },
    { name: 'BP', domain: 'bp.com', patterns: ['bp.com/en/global/corporate/careers'] },
    { name: 'Chevron', domain: 'chevron.com', patterns: ['careers.chevron.com'] },
    { name: 'ExxonMobil', domain: 'exxonmobil.com', patterns: ['corporate.exxonmobil.com/careers'] },
];

export function findMetadataByUrl(url: string): CompanyMetadata | null {
    const lower = url.toLowerCase();
    for (const company of COMPANY_REGISTRY) {
        if (company.patterns.some(p => lower.includes(p.toLowerCase()))) {
            return company;
        }
    }
    return null;
}
